{
 "title": "Hyperledger Fabric",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "# Transações Validas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ledger_transaction_count{transaction_type =\"ENDORSER_TRANSACTION\", validation_code=\"VALID\"})"
    }
   ]
  },
  {
   "title": "# Peers",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(up{job=~\"peer1|peer2\"})"
    }
   ]
  },
  {
   "title": "# Orderers",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(up{job=~\"orderer1|orderer2|orderer3\"})  "
    }
   ]
  },
  {
   "title": "# Transações com Erro",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(sum(ledger_transaction_count{transaction_type =\"ENDORSER_TRANSACTION\", validation_code!=\"VALID\"})) "
    }
   ]
  },
  {
   "title": "Média de Transações Endossadas ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(ledger_transaction_count[10s]) )  by (validation_code)"
    }
   ]
  },
  {
   "title": "Tempo médio de reposta por Peer",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Tempo médio (ms)" }
   ],
   "targets": [
    {
     "expr": "avg(rate(chaincode_shim_request_duration_sum{success=\"true\"}[10s])) by (job)  "
    }
   ]
  }
 ]
}