apiVersion: v1
kind: Service
metadata:
  name: ca-svc
  labels:
    app: ca
spec:
  selector:
    app: ca
  type: NodePort
  ports:
  - port: 7054
    protocol: TCP
    targetPort: 7054
    nodePort: 31054
    name: porta1
  - port: 9443
    protocol: TCP
    targetPort: 9443
    nodePort: 32448
    name: metrica
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ca
  labels:
    app: ca
spec:
  serviceName: ca
  replicas: 1
  selector:
    matchLabels:
      app: ca
  template:
    metadata:
      labels:
        app: ca
    spec:
      volumes:
      - name: nfs-cert
        hostPath:
           path: /blockchain/certificados
      containers:
      - name: ca
        image: hyperledger/fabric-ca:1.4.0
        ports:
        - containerPort: 7054
        - containerPort: 9443
        env:
        - name: FABRIC_CA_HOME
          value: "/etc/hyperledger/fabric-ca-server"
        - name: LICENSE
          value: "accept"
        - name: FABRIC_CA_SERVER_CA_NAME
          value: "ca.ibm.com"
        - name: FABRIC_CA_SERVER_CSR_HOSTS
          value: "ca.ibm.comyaml,localhost,ca-svc"
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "true"
        - name: FABRIC_CA_SERVER_TLS_CERTFILE
          value: "/etc/hyperledger/fabric-ca-server-config/ca.ibm.com-cert.pem"
        - name: FABRIC_CA_SERVER_TLS_KEYFILE
          value: "/etc/hyperledger/fabric-ca-server-config/keyfile"
        volumeMounts:
        - name: nfs-cert
          mountPath: /etc/hyperledger/fabric-ca-server-config
        command: ["sh"]
        args: ["-c", "fabric-ca-server start -c /etc/hyperledger/fabric-ca-server-config/fabric-ca-server-config.yaml --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.ibm.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/keyfile -b admin:adminpw -d"]
