apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
    name: porta1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: nfs-pg-master
        hostPath:
           path: /blockchain/postgres
      containers:
      - name: postgres
        image: postgres:12.0
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_INITDB_ARGS
          value: "-A password"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "adminpw"
        - name: POSTGRES_DB
          value: "fabric"
        volumeMounts:
        - name: nfs-pg-master
          mountPath: /var/lib/postgresql/data
