apiVersion: v1
kind: Service
metadata:
  name: kafka1
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: porta1
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka
    kafka_instance: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka2
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: porta1
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka
    kafka_instance: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka3
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: porta1
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka
    kafka_instance: "3"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-pod1
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka1
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        kafka_instance: "1"
    spec:
      containers:
      - name: kafka
        image: hyperledger/fabric-kafka:0.4.10
        env:
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "103809024"
        - name: KAFKA_REPLICA_FETCH_MAX
          value: "103809024"
        - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLED
          value: "false"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: "2"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "3"
        - name: FAFKA_LOG_RETENTION_MS
          value: "-1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
        - name: KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS
          value: "36000"
        - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
          value: "36000"
        ports:
        - containerPort: 9092
          name: porta1
      imagePullSecrets:
        - name: ibmkey
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-pod2
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka2
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        kafka_instance: "2"
    spec:
      containers:
      - name: kafka
        image: hyperledger/fabric-kafka:0.4.10
        env:
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "103809024"
        - name: KAFKA_REPLICA_FETCH_MAX
          value: "103809024"
        - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLED
          value: "false"
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: "2"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "3"
        - name: FAFKA_LOG_RETENTION_MS
          value: "-1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
        - name: KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS
          value: "36000"
        - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
          value: "36000"
        ports:
        - containerPort: 9092
          name: porta1
      imagePullSecrets:
        - name: ibmkey
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-pod3
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka3
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        kafka_instance: "3"
    spec:
      containers:
      - name: kafka
        image: hyperledger/fabric-kafka:0.4.10
        env:
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "103809024"
        - name: KAFKA_REPLICA_FETCH_MAX
          value: "103809024"
        - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLED
          value: "false"
        - name: KAFKA_BROKER_ID
          value: "3"
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: "2"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "3"
        - name: FAFKA_LOG_RETENTION_MS
          value: "-1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
        - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
          value: "36000"
        - name: KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS
          value: "36000"
        ports:
        - containerPort: 9092
          name: porta1
      imagePullSecrets:
        - name: ibmkey
