apiVersion: v1
kind: Service
metadata:
  name: peer0
  labels:
    app: peer0
spec:
  selector:
    app: peer0
  type: NodePort
  ports:
  - port: 7151
    protocol: TCP
    targetPort: 7151
    nodePort: 31551
    name: porta1
  - port: 7152
    protocol: TCP
    targetPort: 7152
    nodePort: 31552
    name: porta2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: peer-redhat
  labels:
    app: peer0
spec:
  serviceName: peer0
  replicas: 1
  selector:
    matchLabels:
      app: peer0
  template:
    metadata:
      labels:
        app: peer0
    spec:
      volumes:
      - name: nfs-peer0
        hostPath:
           path: /blockchain/peer00
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: peer
        image: hyperledger/fabric-peer:1.4.0
        ports:
        - containerPort: 7151
        - containerPort: 7152
        - containerPort: 7153
        env:
        - name: CORE_LOGGING_PEER
          value: "INFO"
        - name: CORE_CHAINCODE_LOGGING_LEVEL
          value: "INFO"
        - name: CORE_VM_ENDPOINT
          value: "unix:///host/var/run/docker.sock"
        - name: CORE_PEER_LISTENADDRESS
          value: "0.0.0.0:7151"
        - name: CORE_PEER_ID
          value: "peer0"
        - name: CORE_CHAINCODE_BUILDER
          value: "hyperledger/fabric-ccenv:1.4.0"
        - name: CORE_CHAINCODE_NODE_RUNTIME
          value: "hyperledger/fabric-baseimage:0.4.15"
        - name: CORE_PEER_ADDRESS
          value: "peer0:7151"
        - name: CORE_PEER_LOCALMSPID
          value: "redhat"
        - name: CORE_PEER_MSPCONFIGPATH
          value: "/etc/hyperledger/config/msp/users/Admin@redhat.com/msp"
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "true"
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: "CouchDB"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: "couchdbpeer0:5984"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
          value: "admin"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
          value: "adminpw"
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: "peer1:7151"
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: "peer1:7151"
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true"
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false"
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_PEER_GOSSIP_ENDPOINT
          value: "peer0:7151"
        - name: CORE_PEER_TLS_CERT_FILE
          value: "/etc/hyperledger/config/tls/server.crt"
        - name: CORE_PEER_TLS_KEY_FILE
          value: "/etc/hyperledger/config/tls/server.key"
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: "/etc/hyperledger/config/tls/ca.crt"
        volumeMounts:
        - name: nfs-peer0
          mountPath: /etc/hyperledger/config
        - mountPath: /host/var/run/docker.sock
          name: dockersocket
        command: ["peer"]
        args: ["node", "start"]
