apiVersion: v1
kind: Pod
metadata:
  name: cli-peer0-pod
  labels:
    app: cli
spec:
  volumes:
  - name: nfs-cert
    hostPath:
       path: /blockchain/certificados
  - name: dockersocket
    hostPath:
      path: /var/run/docker.sock
  containers:
  - name: clip
    image: hyperledger/fabric-tools:1.4.0
    workingDir: "/opt/gopath/src/github.com/hyperledger/fabric/peer/peer0.redhat.com"
    env:
    - name: TZ
      value: "America/Sao_Paulo"
    - name: GOPATH
      value: "/opt/gopath"
    - name: CORE_VM_ENDPOINT
      value: "unix:///host/var/run/docker.sock"
    - name: FABRIC_LOGGING_SPEC
      value: "INFO"
    - name: CORE_PEER_ID
      value: "peer0"
    - name: CORE_PEER_ADDRESS
      value: "peer0:7151"
    - name: CORE_PEER_LOCALMSPID
      value: "redhat"
    - name: CORE_PEER_TLS_ENABLED
      value: "true"
    - name: CORE_PEER_TLS_CERT_FILE
      value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/peer0.redhat.com/tls/server.crt"
    - name: CORE_PEER_TLS_KEY_FILE
      value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/pper0.redhat/tls/server.key"
    - name: CORE_PEER_TLS_ROOTCERT_FILE
      value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/peer0.redhat.com/tls/ca.crt"
    - name: CORE_PEER_MSPCONFIGPATH
      value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/Admin@redhat.com/msp"
    volumeMounts:
    - name: nfs-cert
      mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer
    - mountPath: /host/var/run/docker.sock
      name: dockersocket
    command: ["/bin/sh"]
    args: ["-c", "sleep 48h"]
