sudo docker pull hyperledger/fabric-tools:1.4
sudo docker pull hyperledger/fabric-tools:latest
sudo docker pull hyperledger/fabric-ccenv:1.4
sudo docker pull hyperledger/fabric-ccenv:latest
sudo docker pull hyperledger/fabric-orderer:1.4
sudo docker pull hyperledger/fabric-peer:1.4
sudo docker pull hyperledger/fabric-peer:latest
sudo docker pull hyperledger/fabric-javaenv:latest
sudo docker pull hyperledger/fabric-couchdb:0.4.15
sudo docker pull hyperledger/fabric-baseimage:0.4.15
sudo docker pull hyperledger/fabric-baseimage:latest
sudo docker pull hyperledger/fabric-tools:1.4.0
sudo docker pull hyperledger/fabric-ca:1.4.0
sudo docker pull hyperledger/fabric-zookeeper:0.4.10
sudo docker pull hyperledger/fabric-kafka:0.4.10
sudo docker pull postgres:12.0
sudo docker pull prom/prometheus:latest
sudo docker pull grafana/grafana:latest
